VERZIJA=CDX
MODUL=PORLD

SRCDOSROOT=$(BASEDOS)\\fmk\\porld\\exe\\
PRGS=e.prg

CS=
ASMS=

EOBJCOPY=echo nista za kopirati
FMK_LIBS=fmk_roba.lib fmk_pi.lib fmk_svi.lib fmk_evn.lib fmk_sec.lib fmk_lok.lib fmk_rule.lib fmk_rab.lib 

SCLIB_LIBS=sc1g_arh.lib sc1g_ba.lib sc1g_cui.lib sc1g_db.lib sc1g_os.lib sc1g_ost.lib sc1g_par.lib sc1g_pr.lib sc1g_sif.lib sc1g_sql.lib sc1g_ut.lib sc2g_app.lib sc2g_db.lib sc1g_rpt.lib sc1g_key.lib sc2g_cui.lib sc_epl2.lib sc_gvp.lib

MODUL_LIBS=por_m.lib por_dok.lib por_un.lib por_db.lib por_sif.lib por_rpt.lib por_ut.lib por_par.lib 

include ../../fmk_lib/Makefile_clipper

lib: exe
